- name: Install from repositories of distribution
  hosts: localhost

  vars:
    core_packages:
      - git
      - vim
      - tmux

  tasks:
    - name: Debian install
      become: true
      ansible.builtin.apt:
        name: "{{ core_packages }}"
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: RHEL install
      become: true
      ansible.builtin.dnf:
        name: "{{ core_packages }}"
        state: present
      when: ansible_facts['os_family'] == "RedHat"
